[package]
org = "xlibb"
name = "graphql_federation_gateway"
version = "0.1.0"
authors = ["Ballerina"]
export=["graphql_federation_gateway"]
keywords = ["graphql", "federation", "gateway"]
repository = "https://github.com/xlibb/graphql-federation-gateway"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[[platform.java17.dependency]]
groupId = "io.xlibb.gateway"
artifactId = "gateway-native"
version = "0.1.0"
path = "../native/build/libs/gateway-native-0.1.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "com.graphql-java"
artifactId = "graphql-java"
version = "20.6"
path="./lib/graphql-java-20.6.jar"

[[platform.java17.dependency]]
groupId = "com.graphql-java"
artifactId = "graphql-java-extended-scalars"
version = "20.0"
path="./lib/graphql-java-extended-scalars-20.0.jar"

[[platform.java17.dependency]]
groupId = "commons-io"
artifactId = "commons-io"
version = "2.11.0"
path="./lib/commons-io-2.11.0.jar"

[[platform.java17.dependency]]
groupId = "org.ballerinalang"
artifactId = "formatter-core"
version = "2201.7.0"
path="./lib/formatter-core-2201.7.0.jar"

[[platform.java17.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-parser"
version = "2201.7.0"
path="./lib/ballerina-parser-2201.7.0.jar"
