[package]
org = "xlibb"
name = "graphql_federation_gateway"
version = "0.1.0"
authors = ["Ballerina"]
export=["graphql_federation_gateway"]
keywords = ["graphql", "federation", "gateway"]
repository = "https://github.com/xlibb/graphql-federation-gateway"
license = ["Apache-2.0"]
distribution = "2201.6.0"

[[platform.java11.dependency]]
groupId = "io.xlibb.gateway"
artifactId = "gateway-native"
version = "0.1.0"
path = "../native/build/libs/gateway-native-0.1.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "com.graphql-java"
artifactId = "graphql-java"
version = "20.0"
path="./lib/graphql-java-20.0.jar"

[[platform.java11.dependency]]
groupId = "com.graphql-java"
artifactId = "graphql-java-extended-scalars"
version = "20.0"
path="./lib/graphql-java-extended-scalars-20.0.jar"

[[platform.java11.dependency]]
groupId = "commons-io"
artifactId = "commons-io"
version = "2.11.0"
path="./lib/commons-io-2.11.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "formatter-core"
version = "2201.6.0"
path="./lib/formatter-core-2201.6.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-lang"
version = "2201.6.0"
path="./lib/ballerina-lang-2201.6.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-parser"
version = "2201.6.0"
path="./lib/ballerina-parser-2201.6.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-runtime"
version = "2201.6.0"
path="./lib/ballerina-runtime-2201.6.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-tools-api"
version = "2201.6.0"
path="./lib/ballerina-tools-api-2201.6.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "central-client"
version = "2201.6.0"
path="./lib/central-client-2201.6.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "maven-resolver"
version = "2201.6.0"
path="./lib/maven-resolver-2201.6.0.jar"

[[platform.java11.dependency]]
groupId = "com.github.zafarkhaja"
artifactId = "java-semver"
version = "0.9.0"
path="./lib/java-semver-0.9.0.jar"

[[platform.java11.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-compress"
version = "1.21"
path="./lib/commons-compress-1.21.jar"

[[platform.java11.dependency]]
groupId = "com.squareup.okhttp3"
artifactId = "okhttp"
version = "3.14.0"
path="./lib/okhttp-3.14.0.jar"

[[platform.java11.dependency]]
groupId = "com.squareup.okio"
artifactId = "okio"
version = "2.2.2"
path="./lib/okio-2.2.2.jar"

[[platform.java11.dependency]]
groupId = "org.jetbrains.kotlin"
artifactId = "kotlin-stdlib"
version = "1.2.60"
path="./lib/kotlin-stdlib-1.2.60.jar"

[[platform.java11.dependency]]
groupId = "org.ow2.asm"
artifactId = "asm"
version = "7.2"
path="./lib/asm-7.2.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-common"
version = "4.1.77.Final"
path="./lib/netty-common-4.1.77.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-buffer"
version = "4.1.77.Final"
path="./lib/netty-buffer-4.1.77.Final.jar"
